# Generated by Django 2.2 on 2020-01-19 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desciption',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='new_app.Description'),
        ),
    ]
